name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: angelajacinto
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          COLOR_SNAKE: "#FFC0CB"        # Pink snake
          BACKGROUND_COLOR: "#00000000"  # Transparent

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

